# frontend/Dockerfile.dev

FROM node:18

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the code
COPY . .

# Expose React dev server port
EXPOSE 3000

# Start React app in development mode with hot reload
CMD ["npm", "start"]
