version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: gotasks-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: gotasks-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  frontend:
    container_name: gotasks-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
