version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: gotasks-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: gotasks-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo

volumes:
  mongo-data:
